### PR TITLE
Ftr/fa solid only

### PR DESCRIPTION
**Pull request by dkastl**
This pull request is based on the work done in https://github.com/farend/redmine_theme_farend_bleuclair/pull/71

It makes the following changes:
- uses exclusively solid type webfont and removes regular style font as discussed in https://github.com/farend/redmine_theme_farend_bleuclair/pull/71#issuecomment-1746344628
- removes font related mixins
- adds `typography.scss`
- simplifions and restructuring

### CODE REVIEW

**Comment by ishikawa999** [comment]
Thank you! I have multiple tasks on my plate, so there might be a slight delay in my review.

**Comment by ishikawa999** [comment]
@dkastl 
Since I'm not particularly adept at CSS or JavaScript, your contributions in these fields are invaluable to me.

**Comment by ishikawa999** [comment]
I intend to use this theme for a short period to ensure that the changes in icons have not made it more difficult to understand. Please bear with me, as it may take a bit more time before we are ready to proceed with the merge.

**Comment by ishikawa999** [comment]
> @dkastl I have collected some feedback on the changes made by this pull request. Considering the feedback points, I think it might be better not to completely unify the icons to Solid style.
> 
> * It's better not to change the font size.
> * Changing icon-fav-off (icon when not watched) to Solid could lead to misinterpretation as a 'watched' state due to it being filled in black. It's more appropriate to maintain its current Regular style.
> * In the Gantt chart view and other areas, switching fa-sticky-note to a filled black icon makes it too prominent and darkens the screen's appearance.
> * The current jstToolbar 'pre' and highlight icons should remain as they are. It is confusing to use the fa-code icons in a different context than before.

@dkastl 
I find it difficult to merge this pull request as described above.
I regret that I am unable to merge your deliverables, may I close this pull request?

**Comment by dkastl** [comment]
OK, no problem. Thanks a lot for looking at it.

**Comment by ishikawa999** [comment]
@dkastl  Many thanks.

**Pull request closed without merging**
