### PR TITLE
Improves webpack and updates Font Awesome

### PR DESCRIPTION
**Pull request by dkastl**
This pull request does the following:

- installs "Font Awesome 6 Free" through NPM
- manages fonts through Webpack
- manages images through Webpack
- Embeds small SVG's (<10KB) as data URL directly in the CSS
- adds all files in `stylesheets` and `javascripts` to the pre-commit hook
- updates the Webpack configuration

### CODE REVIEW

**Comment by dkastl** [comment]
@ishikawa999 , let me know what you think about updating to Font Awesome 6.

I saw that two variants are used: `Solid` and `Regular`. But `Regular` has a lot less icons than `Solid`. Wouldn't it be easier to use only icons of type `Solid`? This would simplify the code.

**Comment by dkastl** [comment]
Let me share this link to clarify the previous comment: https://fontawesome.com/search?o=r&m=free
Looking at the sidebar it shows that there are 1390 solid icons and 163 regular icons, so I would assume that for every solid icon there exists a regular icon as well.

**Comment by ishikawa999** [comment]
@dkastl 
I agree with your thoughts. There doesn't seem to be a compelling reason to use both Solid and Regular icons. Switching from Regular to Solid icons doesn't appear to make things less readable, so unifying to Solid icons seems like a good approach.

**Comment by dkastl** [comment]
Thank you! I thought there might be certain reasons for your choices, but if you agree with using solid type only, then this probably makes the code more readable and also loads one font file less.

I will create another pull request for this then.

**Comment by ishikawa999** [comment]
@dkastl 

I apologize for the delay in reviewing. I ran the code on my end and didn't find any issues, so I'm planning to merge it.

**Review by ishikawa999 — APPROVED** [review]

**Pull request merged**
